### PR TITLE
Include vanilla wabt charts to notebook

### PR DESCRIPTION
**Pull request by hugo-dc**
Fixes: https://github.com/ewasm/benchmarking/issues/132

### CODE REVIEW

**Comment by axic** [comment]
How come this did not update the images?

**Comment by hugo-dc** [comment]
Because the [images are not saved to a file,](https://github.com/ewasm/benchmarking/issues/111) only visible in the notebook;  
But I realize it doesn't make sense to merge this one, before merging https://github.com/ewasm/benchmarking/pull/131/files

**Comment by jwasinger** [comment]
For some reason, the benchmarks for 'vanilla-wabt' are not in the repo.

**Comment by axic** [comment]
Does not seems to be part of the benchmark run: https://github.com/ewasm/benchmarking/blob/master/wasm-engines/docker/wasm-engines-bench.Dockerfile

**Comment by axic** [comment]
Reverted the failure introduced in #103 (as mentioned in https://github.com/ewasm/benchmarking/pull/133#issuecomment-666761298).

@jwasinger @hugo-dc can you check and merge?

**Comment by jwasinger** [comment]
I don't see 'vanilla-wabt' in any of the generated charts.  I think it has to be explicitly enabled in the right part(s) of the notebook to appear.

I would opt to keep vanilla wabt in the dataset but not explicitly enable it on any charts unless we want to.

**Pull request merged**
