### PR TITLE
add script generated from notebook

### PR DESCRIPTION
**Pull request by jwasinger**
Generated from `jupyter nbconvert --to script wasm-engines.ipynb`.  This could be a starting point for discontinuing use of the notebook.

### CODE REVIEW

**Comment by axic** [comment]
Is it possible to convert bidirectionally?

I guess it is easier to craft new charts visually in the notebook, but it is an absolute pain dealing with the notebook in a deterministic way.

**Comment by jwasinger** [comment]
Looks like there are tools to convert from script to notebook: https://github.com/jupyter/nbconvert/issues/452

**Comment by axic** [comment]
I think this should have been merged after everything else. Now we have two scripts, and only one of them is tested on CI.

**Comment by jwasinger** [comment]
> What happens now when merging the other PRs changing the notebook? WIll all those PRs need to be changed to also change this script?

I'd opt to translate the notebook changes in other open PRs into this script.

Sorry for optimistically merging this, we can just regenerate the script later after merging other notebook changes.

**Pull request merged**
