### PR TITLE
Update to fizzy 0.2.0

### PR DESCRIPTION
**Pull request by axic**
Part of #81.

### CODE REVIEW

**Comment by axic** [comment]
Should we bump the docker version of fizzy?

**Comment by jwasinger** [comment]
> Should we bump the docker version of fizzy?

Your call.  we can, but could also wait until the report is released before we start actually following the versioning scheme.  (nobody is going to rely on fizzy:1 afaik).

**Comment by jwasinger** [comment]
Also maybe should rebase the fizzy branches used for scout engines benchmarks?

**Comment by axic** [comment]
> Also maybe should rebase the fizzy branches used for scout engines benchmarks?

Yes, will do that, but that's a separate PR. Those branches are already close to 0.2.0 in terms of performance.

**Comment by axic** [comment]
@jwasinger @hugo-dc I think this will note work, need to also change `wasm-engines/fizzy.sh` to include the signature line in this:
```
echo test   > testcase.inputs   # 1. Test name
echo $1    >> testcase.inputs   # 2. Function name
echo $'\n' >> testcase.inputs   # 3. Function parameters
echo $'\n' >> testcase.inputs   # 4. Initial Memory
echo $'\n' >> testcase.inputs   # 5. Expected result
echo $'\n' >> testcase.inputs   # 6. Expected memory
```

**Pull request merged**
