### PR TITLE
Update benchmarks

### PR DESCRIPTION
**Pull request by jwasinger**
depends on #134

### CODE REVIEW

**Comment by axic** [comment]
Fizzy is missing from the new charts.

**Comment by jwasinger** [comment]
Which charts?

**Comment by jwasinger** [comment]
`wamr-aot` also missing from the charts/dataset

**Comment by jwasinger** [comment]
`images/bignums-bls12-pairings-host-func-variations-exec-startup-time.png` doesn't look good. Should probably remove a bar or two on that graph to fix the text layout.

**Pull request merged**
