### PR TITLE
Add rust benchmarks for ecadd, instructions for compiling using life

### PR DESCRIPTION
**Pull request by jwasinger**
Also changes the overall directory structure around to accommodate the new benchmarks.

### CODE REVIEW

**Comment by poemm** [comment]
BTW it is great that you are doing this discovery work, will be very useful.

**Comment by cdetrio** [comment]
So this contains one .wasm benchmark (as opposed to an ewasm benchmark). Let's coordinate and come up with a systematic way to generate all the .wasm benchmark files. Not that we will generate them automatically, but that they will be consistent in number of inputs and so on.

**Comment by jwasinger** [comment]
All of the pure-wasm performance benchmarks have a single entrypoint without arguments and return nothing.  I guess we can write them to all have the same number of benchmark inputs per test case.

**Comment by jwasinger** [comment]
Ok @poemm PR is updated and ready.

**Comment by poemm** [comment]
Looks great! I will try to execute this when I get a chance. I am merging it.

Because this repository is for information gathering and not critical for anything, I see no problem with you merging stuff yourself if it improves your productivity, if you have the privileges. But I am happy to review if I am pinged.

**Pull request merged**
