### PR TITLE
standardize node version (12.18.2 active LTS)

### PR DESCRIPTION
**Pull request by jwasinger**
closes https://github.com/ewasm/benchmarking/issues/78

### CODE REVIEW

**Comment by axic** [comment]
@jwasinger @cdetrio what's left here?

**Comment by jwasinger** [comment]
@axic nothing.  I think it can be merged.

**Comment by axic** [comment]
Readme needs to be updated too.

Also what is the effect on the charts?

**Comment by jwasinger** [comment]
> Also what is the effect on the charts?

I'm waiting on the benchmarks to finish so I can generate them.

**Comment by jwasinger** [comment]
no noticeable differences: https://github.com/ewasm/benchmarking/pull/144

**Comment by axic** [comment]
> Readme needs to be updated too.

Ah this wasn't done.

**Pull request merged**
