### PR TITLE
remove old makefile

### PR DESCRIPTION
**Pull request by poemm**

### CODE REVIEW

**Comment by axic** [comment]
Why is it better removing the makefile? It is useful to recreate the test cases.

**Comment by poemm** [comment]
Makefile is outdated and unused. It is more flexible to have explicit `clang` commands. If a Makefile becomes more convenient, then I will re-evaluating it.

**Comment by axic** [comment]
Ok, in that case a better commit message (and PR description) helps in understanding the reason behind it, e.g. "Remove outdated makefile".

Is it possible though to fix the makefile instead? The current README is quite huge and having scripts/makefile seems to be way less error prone than expected users' to copy & paste from the README.

**Comment by poemm** [comment]
I want to give Jared as much freedom as possible, and not burden him with the limitations of a Makefile. Once I see his compile commands and directory structure, then I will consider reintroducing a Makefile. I agree that Makefiles can be useful, but not yet.

**Pull request merged**
