### PR TITLE
Add EVM benchmarks results

### PR DESCRIPTION
**Pull request by hugo-dc**

### CODE REVIEW

**Comment by hugo-dc** [comment]
> Should include stats about the machine these were ran on. We should probably run them all on the same VM.

Where is a gut place to put machine stats?. All clients used to be in a single Dockerfile, this was changed as suggested in this issue: https://github.com/ewasm/benchmarking/issues/22

**Comment by jwasinger** [comment]
We should run all the benchmarks at once and update all the resulting data-sets alongside https://github.com/ewasm/benchmarking/blob/master/benchmark_results_data/cpuinfo.txt .

That is, assuming you aren't running these benchmarks on the same VM as is currently referenced in `cpuinfo.txt1` in the master branch.

**Comment by hugo-dc** [comment]
@jwasinger ok, I'm running the EVM benchmarks in the same machine described in `cpuinfo.txt`.

**Comment by jwasinger** [comment]
@hugo-dc can you push those benchmarks?

**Comment by jwasinger** [comment]
I'm just gonna merge this so I can add the EVM data to some of the charts in https://github.com/ewasm/benchmarking/pull/29 .  We can re-run all the benchmarks on the same machine and push them before the 1st part of the report goes out.

**Pull request merged**
