### PR TITLE
save all charts to a file, rename evm384 charts

### PR DESCRIPTION
**Pull request by hugo-dc**
Fixes: https://github.com/ewasm/benchmarking/issues/111

### CODE REVIEW

**Comment by cdetrio** [comment]
Needs to be rebased I guess?

**Comment by cdetrio** [comment]
Not all charts are saved because not all are used in the report. Some of them are just scratch charts or old charts, some are there left in the notebook purposefully because they are useful reference/examples but don't demonstrate any particular point (and so were not included in the report).

I don't mind merging them all as image files, just an fyi for later why some image files are not used in the report.

**Comment by axic** [comment]
> I don't mind merging them all as image files, just an fyi for later why some image files are not used in the report.

It is not fine not using them in the report, but if we generate them, they should be saved. Or just deleted.

**Comment by axic** [comment]
Not sure why this is failing, perhaps @hugo-dc uses a different python version? Currently stuff is locked to @cdetrio's system.

**Comment by jwasinger** [comment]
> > I don't mind merging them all as image files, just an fyi for later why some image files are not used in the report.
> 
> It is not fine not using them in the report, but if we generate them, they should be saved. Or just deleted.

IMO, unused charts should be commented in the script/notebook and not saved/included in the repo.

**Comment by hugo-dc** [comment]
CircleCI was generating the charts using newer `evm_benchmarks.csv` data, I regenerated the charts again with the new data.

If there are charts only used for "reference" and not used in the report I would suggest to move it to a different notebook if we really want to keep them, or remove them as @axic suggested.. 

I will take a look at the report and the generated charts to know which charts are not going to be saved.

**Pull request merged**
